# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('editor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Conference',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.TextField(blank=True)),
                ('issn', models.CharField(blank=True, max_length=15, null=True)),
                ('alt_issn', models.CharField(blank=True, max_length=15, null=True)),
                ('isbn', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Journal',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('num', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('reference', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
                ('pages', models.TextField(blank=True, null=True)),
                ('nauthors', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Paper',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('identificador', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('fund', models.TextField(blank=True, null=True)),
                ('nresearchers', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('for_field', models.CharField(blank=True, db_column='for', max_length=1, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Quality',
            },
        ),
        migrations.CreateModel(
            name='QualityIndex',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('web', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Quality_index',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('login', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('surnames', models.TextField()),
                ('extern', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=5, null=True)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Researcher',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('paper', models.ForeignKey(db_column='paper', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='querys.Paper')),
                ('position', models.IntegerField(primary_key=True, serialize=False)),
                ('signature', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='ConferencePaper',
            fields=[
                ('paper', models.ForeignKey(db_column='paper', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='querys.Paper')),
                ('edition', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.TextField(blank=True, null=True)),
                ('editor', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'Conference_paper',
            },
        ),
        migrations.CreateModel(
            name='ConferenceQuality',
            fields=[
                ('conference', models.ForeignKey(db_column='conference', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='querys.Conference')),
                ('quality', models.ForeignKey(db_column='quality', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='querys.Quality')),
            ],
            options={
                'db_table': 'Conference_quality',
            },
        ),
        migrations.CreateModel(
            name='JournalPaper',
            fields=[
                ('num', models.ForeignKey(db_column='num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='querys.Paper', unique=True)),
                ('issue', models.CharField(blank=True, max_length=10, null=True)),
                ('volume', models.CharField(blank=True, max_length=10, null=True)),
                ('journal', models.ForeignKey(blank=True, db_column='journal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='querys.Journal')),
            ],
            options={
                'db_table': 'Journal_paper',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('paper', models.ForeignKey(db_column='paper', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='querys.Paper')),
                ('link', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Media',
            },
        ),
        migrations.CreateModel(
            name='PaperQuality',
            fields=[
                ('paper', models.ForeignKey(db_column='paper', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='querys.Paper')),
                ('quality', models.ForeignKey(db_column='quality', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='querys.Quality')),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Paper_quality',
            },
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('project', models.ForeignKey(db_column='project', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='querys.Project')),
                ('researcher', models.ForeignKey(db_column='researcher', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='querys.Researcher')),
                ('roll', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Participate',
            },
        ),
        migrations.AddField(
            model_name='quality',
            name='qindex',
            field=models.ForeignKey(blank=True, db_column='qindex', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='querys.QualityIndex'),
        ),
        migrations.AlterUniqueTogether(
            name='participate',
            unique_together=set([('project', 'researcher')]),
        ),
        migrations.AlterUniqueTogether(
            name='paperquality',
            unique_together=set([('paper', 'quality')]),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together=set([('paper', 'link')]),
        ),
        migrations.AlterUniqueTogether(
            name='conferencequality',
            unique_together=set([('conference', 'quality')]),
        ),
        migrations.AddField(
            model_name='conferencepaper',
            name='conference',
            field=models.ForeignKey(blank=True, db_column='conference', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='querys.Conference'),
        ),
        migrations.AddField(
            model_name='author',
            name='researcher',
            field=models.ForeignKey(blank=True, db_column='researcher', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='querys.Researcher'),
        ),
        migrations.AlterUniqueTogether(
            name='journalpaper',
            unique_together=set([('num', 'journal')]),
        ),
        migrations.AlterUniqueTogether(
            name='conferencepaper',
            unique_together=set([('paper', 'conference')]),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set([('position', 'paper')]),
        ),
    ]
