# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='position',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='paperquality',
            name='paper',
            field=models.ForeignKey(db_column='paper', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='querys.Paper'),
        ),
    ]
